### ISSUE TITLE
Some videos can't be played

### ISSUE THREAD

**Issue by st-stalker** [GeraldBrooks/youtube#15]
Hello,

If you try to search for any music video (we reproduced bug with search query "Nensi iva", btw not the best song imo) and try to play any video from result - you'll get error "the video is unavailable", but the video can be played from pc and smart tv app from the same IP.

No difference - if we're using our generated API keys, or provided on github (https://raw.githubusercontent.com/GeraldBrooks/youtube/master/config.json).

**Comment by ch3g3v4r4** [comment]
Hello,

Yes i can confirm that i am having the same issue... Is this problem related to google ad's?

Will this be fixed soon?

Thx,

**Comment by GeraldBrooks** [comment]
Fixed at 2.0.1

**Comment by connected9** [comment]
Thanks Very Much ,
installed 2.0.1 . and facing same problem " sorry can't play video "

any idea ?
