### ISSUE TITLE
Video not available

### ISSUE THREAD

**Issue by AndersonDan** [GeraldBrooks/youtube#27]
Some videos run perfectly, others do not, regardless of the length of the video.

My Stalker version: 5.1.1
My youtube version: 2.1.2 (this has already occurred in other versions)

See how the error is occurring: https://www.youtube.com/watch?v=i3Ca0FLW2Qk
The video is playing correctly: https://www.youtube.com/watch?v=xMvKpEFr17M
The video not available: https://www.youtube.com/watch?v=b4ozdiGys5g

It has no log of the response, and also does not have the release.js source code to help, so we could fix it ourselves.

I suspect it may be something copyright, if it is, it should be removed from search and from listings that exist. There is a lot of customer complaint.

Refer to #22

**Comment by vicentroca** [comment]
Same problem here :(
