### ISSUE TITLE
arabic characters

### ISSUE THREAD

**Issue by rajaie1976** [GeraldBrooks/youtube#3]
hi ,
there is some problems with the Arabic characters , they are repeated and  there are missing other characters ,
please if you need any help regarding this let me know.
warm regards

**Comment by GeraldBrooks** [comment]
Hello. 
If u can help me with arabic keyboard it was be awesome.
I take arabic from https://en.wikipedia.org/wiki/Arabic_keyboard, will check it again in version 1.5.9, or if you have time, explain me my mistakes.

**Comment by rajaie1976** [comment]
you have repeated characters in the second line , and missing other characters .
repeated ن ن
missing ذ
