### ISSUE TITLE
Video not available

### ISSUE THREAD

**Issue by nikviso** [GeraldBrooks/youtube#30]
Hello!

Some days ago appeared error ‘Video not available‘. I have the latest version of Youtube 2.1.3

**Comment by mikka31** [comment]
The same problem. The most of the video are not available.

**Comment by RuslanLi** [comment]
Yeah. Same thing ((

**Comment by geoline** [comment]
The same problem...

**Comment by turalo** [comment]
it's same everywhere !!!
